server:
  port: 9090
  servlet:
    context-path: /auth-key  


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/eazybank?useSSL=false
    password: Ram16102000@
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/TaskManagement/protocol/openid-connect/certs
kc:
  realm: eazybites
  admin:
    password: admin
    username: admin
  auth-server-url: http://localhost:8081
  client-id: admin-cli
  grant-type: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/


management:
  tracing:
    sampling:
      probability: 1.0  # in productionn 2.6
  
